"""A deterministic LLMClient that needs no API key.

This is what the demo pipeline runs against by default (see Settings.llm_provider)
so the UI has real, navigable per-stage content to show without requiring
OPENAI_API_KEY. It is not a test double for pinning exact routing behaviour --
see tests/helpers.py's ScriptedLLMClient for that.
"""

from __future__ import annotations

import json
import re

from ai_fde.core.models import LLMResponse, LLMUsage
from ai_fde.core.prompts.composer import GENERATION_CONTEXT_SENTINEL
from ai_fde.core.prompts.registry import extract_title

_VALIDATOR_MARKER = "stronger, independent reviewer"  # from prompts/_shared/validator_system.md
_REPAIR_MARKER = "You are repairing a stage artifact"  # from prompts/repair/repair.md

_DRAFT_SECTION_RE = re.compile(
    r"## The draft that failed validation\n\n(.*?)\n\n## Why it failed", re.DOTALL
)
_USE_CASE_RE = re.compile(r"## Use case\n\n### ([^\n(]+)")

_H2_HEADING_RE = re.compile(r"(?m)^##[ \t]+(.+?)[ \t]*$")


def _stage_body_headings(prompt: str) -> list[str]:
    """A stage prompt that declares `required_sections` in its front matter is
    expected (by house style) to organise its own instructions under those exact
    `##` headings -- so harvesting `##` lines from the stage body (everything after
    `compose_generation_prompt`'s sentinel) reproduces the required structure
    without FakeLLMClient needing to know any stage by name. Stages with no such
    headings (the pipeline's original five) fall back to the generic Summary/Notes
    placeholder below, unchanged."""
    parts = prompt.split(GENERATION_CONTEXT_SENTINEL, 1)
    stage_body = parts[1] if len(parts) == 2 else prompt
    return _H2_HEADING_RE.findall(stage_body)


class FakeLLMClient:
    def __init__(self, *, validator_score: int = 88) -> None:
        self._validator_score = validator_score

    async def complete(self, *, model: str, system: str, prompt: str) -> LLMResponse:
        # Repair calls also carry the validator persona as their system message
        # (the validator model acts as generator for the repair pass), so the
        # repair marker must be checked before the validator marker.
        if _REPAIR_MARKER in prompt:
            content = self._fake_repair(prompt)
        elif _VALIDATOR_MARKER in system:
            content = self._fake_validation(prompt)
        else:
            content = self._fake_generation(prompt)

        usage = LLMUsage(
            prompt_tokens=len(prompt) // 4,
            completion_tokens=len(content) // 4,
            total_tokens=(len(prompt) + len(content)) // 4,
            cost_usd=0.0,
        )
        return LLMResponse(content=content, model=model, usage=usage)

    def _fake_validation(self, prompt: str) -> str:
        score = self._validator_score
        report = {
            "overall_score": score,
            "verdict": "pass" if score >= 80 else "fail",
            "criteria": [
                {"name": "completeness", "score": score, "weight": 0.25, "comment": "Generated by FakeLLMClient."},
                {"name": "grounding", "score": score, "weight": 0.25, "comment": "Generated by FakeLLMClient."},
                {"name": "structure", "score": score, "weight": 0.25, "comment": "Generated by FakeLLMClient."},
                {"name": "specificity", "score": score, "weight": 0.25, "comment": "Generated by FakeLLMClient."},
            ],
            "issues": []
            if score >= 80
            else [
                {
                    "severity": "major",
                    "location": "document",
                    "problem": "FakeLLMClient issued a below-threshold score for demo purposes.",
                    "fix": "Regenerate with more specific, grounded content.",
                }
            ],
            "repair_instructions": "" if score >= 80 else "Be more specific and ground every claim.",
        }
        return json.dumps(report)

    def _fake_repair(self, prompt: str) -> str:
        match = _DRAFT_SECTION_RE.search(prompt)
        draft = match.group(1).strip() if match else "(original draft unavailable)"
        return draft + "\n\n> _Repaired by FakeLLMClient: added grounding detail per validator feedback._"

    def _fake_generation(self, prompt: str) -> str:
        stage_title = extract_title(prompt) or "Stage Artifact"

        use_case_match = _USE_CASE_RE.search(prompt)
        use_case_name = use_case_match.group(1).strip() if use_case_match else "the uploaded use case"

        preamble = (
            f"# {stage_title}\n\n"
            f"_Generated by FakeLLMClient from `{use_case_name}`. This is a deterministic demo "
            f"artifact -- point AI_FDE at a real provider (see Settings.llm_provider) for actual "
            f"model output._\n\n"
        )

        headings = _stage_body_headings(prompt)
        if headings:
            sections = "\n\n".join(
                f"## {heading}\n\n"
                f"This section would normally be produced by the generator model reasoning over "
                f"the use case, the evidence documents, and the accepted artifacts from prior "
                f"stages.\n\n"
                f"- **Assumption:** no real LLM call was made; this content is a structural "
                f"placeholder."
                for heading in headings
            )
            return preamble + sections + "\n"

        return (
            preamble + "## Summary\n\n"
            f"This section would normally be produced by the generator model reasoning over the "
            f"use case, the evidence documents, and the accepted artifacts from prior stages.\n\n"
            f"## Notes\n\n"
            f"- **Assumption:** no real LLM call was made; this content is a structural placeholder.\n"
            f"- Open question: what does the real generator model produce here for this use case?\n"
        )
